/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer } from "ethers";
import { Provider } from "@ethersproject/providers";

import type { IGreeter } from "../IGreeter";

export class IGreeter__factory {
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IGreeter {
    return new Contract(address, _abi, signerOrProvider) as IGreeter;
  }
}

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256",
        name: "a",
        type: "uint256",
      },
    ],
    name: "foo",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
];
