/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer } from "ethers";
import { Provider } from "@ethersproject/providers";

import type { IPlagiarism } from "../IPlagiarism";

export class IPlagiarism__factory {
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IPlagiarism {
    return new Contract(address, _abi, signerOrProvider) as IPlagiarism;
  }
}

const _abi = [
  {
    inputs: [
      {
        internalType: "string",
        name: "new_code",
        type: "string",
      },
      {
        internalType: "string",
        name: "unique_code",
        type: "string",
      },
    ],
    name: "getSimilarity",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
];
