/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
  Contract,
  ContractTransaction,
  Overrides,
  CallOverrides,
} from "ethers";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";
import { TypedEventFilter, TypedEvent, TypedListener } from "./commons";

interface CopyrightInterface extends ethers.utils.Interface {
  functions: {
    "checkSimilarity(string,string)": FunctionFragment;
    "similarity()": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "checkSimilarity",
    values: [string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "similarity",
    values?: undefined
  ): string;

  decodeFunctionResult(
    functionFragment: "checkSimilarity",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "similarity", data: BytesLike): Result;

  events: {};
}

export class Copyright extends Contract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  listeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter?: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): Array<TypedListener<EventArgsArray, EventArgsObject>>;
  off<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  on<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  once<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeListener<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeAllListeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): this;

  listeners(eventName?: string): Array<Listener>;
  off(eventName: string, listener: Listener): this;
  on(eventName: string, listener: Listener): this;
  once(eventName: string, listener: Listener): this;
  removeListener(eventName: string, listener: Listener): this;
  removeAllListeners(eventName?: string): this;

  queryFilter<EventArgsArray extends Array<any>, EventArgsObject>(
    event: TypedEventFilter<EventArgsArray, EventArgsObject>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEvent<EventArgsArray & EventArgsObject>>>;

  interface: CopyrightInterface;

  functions: {
    checkSimilarity(
      new_code: string,
      unique_code: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    "checkSimilarity(string,string)"(
      new_code: string,
      unique_code: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    similarity(overrides?: CallOverrides): Promise<[BigNumber]>;

    "similarity()"(overrides?: CallOverrides): Promise<[BigNumber]>;
  };

  checkSimilarity(
    new_code: string,
    unique_code: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  "checkSimilarity(string,string)"(
    new_code: string,
    unique_code: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  similarity(overrides?: CallOverrides): Promise<BigNumber>;

  "similarity()"(overrides?: CallOverrides): Promise<BigNumber>;

  callStatic: {
    checkSimilarity(
      new_code: string,
      unique_code: string,
      overrides?: CallOverrides
    ): Promise<void>;

    "checkSimilarity(string,string)"(
      new_code: string,
      unique_code: string,
      overrides?: CallOverrides
    ): Promise<void>;

    similarity(overrides?: CallOverrides): Promise<BigNumber>;

    "similarity()"(overrides?: CallOverrides): Promise<BigNumber>;
  };

  filters: {};

  estimateGas: {
    checkSimilarity(
      new_code: string,
      unique_code: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    "checkSimilarity(string,string)"(
      new_code: string,
      unique_code: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    similarity(overrides?: CallOverrides): Promise<BigNumber>;

    "similarity()"(overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    checkSimilarity(
      new_code: string,
      unique_code: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    "checkSimilarity(string,string)"(
      new_code: string,
      unique_code: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    similarity(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "similarity()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;
  };
}
